### ISSUE TITLE
Should PyTorch be upgraded to support 50 series GPUs?

### ISSUE THREAD

**Issue by harveyff** [ace-step/ACE-Step#267]
Hi guys,
This is a great project, but it currently cannot run on 50 series GPUs. It seems that the version of PyTorch is too low. Have you considered upgrading it to support 50 series GPUs?
```
/opt/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA GeForce RTX 5090 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

```

**Comment by soundmountain** [comment]
Hi, I am currently running this project on a rtx 5070 ti. Its been a while since I set this up, so I dont remember exactly the steps, but what I basically did was, create and activate a virtual environment with python 3.10.6 and install from that url:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

the /cu128 at the end of the url is the correct version for 50 series gpus. hope you get it up and running.

**Comment by joojie** [comment]
ok - after reinstalling (w/ python 3.10 not 3.11) it worked and its excellent! thanks to all who contributed! here's a step by step guide:

1. MiniConda link (requires registration on the Anaconda site) -  https://repo.anaconda.com/miniconda/Miniconda3-py310_25.5.1-0-Windows-x86_64.exe

1.1  Install Mini Conda select all users, clear cache, register as the default python installation, (anaconda) register environmental variable PATH so the conda commands are understood in the terminal.

1.2 create environment variable  for conda in the ACE Step Folder you created during the git

1.3 after creating the virtual environment send the conda init command

1.4 then close out and reopen the terminal

1.5 now activate the ace_step environment

1.6 replace the pytorch fetch with:
  
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

1.7 run ACE Step as directed.
